defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

collections_dir: categories

collections:
  species:
    output: true
  locations:
    output: true
  games:
    output: true
  characters:
    output: true
  events:
    output: true
  irl:
    output: true
  misc:
    output: true

kramdown:
  parse_block_html: true
